name: Bug Report
description: Report a bug with AIBlue
body:
  - type: markdown
    attributes:
      value: |
        - Write a descriptive issue title above.
        - Search [open](https://github.com/kthecoder/AIBlue/issues) and [closed](https://github.com/kthecoder/AIBlue/issues?q=is%3Aissue%20state%3Aclosed) issues to ensure it has not already been reported.
  - type: Input
    attributes:
      label: AIBlue Version
      description: >
        Specify the Git commit hash of your AIBlue build.
      placeholder: Godot.v4.4.AIBlue [92bee43ad]
    validations:
      required: true

  - type: input
    attributes:
      label: System Information
      description: |
        Specify the OS version.
      placeholder: Windows 11
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue Description
      description: |
        Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
        You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
    validations:
      required: true
