blank_issues_enabled: false

contact_links:
  - name: AI Blue Proposals
    url: https://github.com/kthecoder/AIBlue
    about: Please submit feature proposals on the Godot proposals repository, not here.

  - name: AI Blue Community Channels
    url: https://aveyrin.com/discord
    about: Please ask for technical support in , not here.
